@startuml
actor Usuario
participant View
participant Controller
participant Service
participant Repository

Usuario -> View: solicita consulta(id)
    View -> Controller: request_consulta(id)
    Controller -> Service: consultar_usuario(id)
    Service -> Repository: buscar_por_id(id)
    Repository --> Service: dados_usuario

alt usuario encontrado 
    Service --> Controller: usuario
    Controller --> View: resposta(usuario)
    View --> Usuario: exibe dados
else usuario não encontrado 
     Service --> Controller: usuario nao encontrado
     Controller --> View: resposta(usuario)

end
    View --> Usuario: exibe dados
@enduml
